In [1]:
# Create a practice set of random latitude and longitude combinations.
x = [25.12903645, 25.92017388, 26.62509167, -59.98969384, 37.30571269]
y = [-67.59741259, 11.09532135, 74.84233102, -76.89176677, -61.13376282]
coordinates = zip(x, y)

In [2]:
# Use the citipy module to determine city based on latitude and longitude.
from citipy import citipy

In [3]:
# Use the tuple() function to display the latitude and longitude combinations.
for coordinate in coordinates:
    print(citipy.nearest_city(coordinate[0], coordinate[1]).city_name,
          citipy.nearest_city(coordinate[0], coordinate[1]).country_code)

cockburn town tc
gat ly
parvatsar in
punta arenas cl
saint george bm


In [4]:
# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

0

In [5]:
# Import the NumPy module.
import numpy as np

In [7]:
#To get more than 500 cities, increase your size limit on the np.random.uniform() 6.1.5
np.random.uniform(-90.000, 90.000, size=50)

array([ 72.56257696,  39.18876372,  73.40301462, -54.45215425,
       -83.89736728, -50.70515735, -85.98057035,  63.60631188,
        81.11568641, -15.90498757,  69.07083308,  60.38101745,
        23.86923871,  64.48997327, -81.8332579 ,  -7.47755723,
       -80.26613997, -37.2243905 , -63.86345585, -75.20960976,
        60.85294491,  14.50948531,  -8.58438848,  87.52151216,
       -62.95618044, -60.55786764,  44.54914483,  22.54880469,
        40.47287627,  43.86513741,   3.54396197, -11.23026127,
       -46.21972896,   7.88250807,  15.05165696, -10.45502024,
        73.34826448, -47.19532659,  67.2288736 ,  89.78349516,
        59.67185438,  15.61213975,   4.57046404,  43.03369085,
        51.76485686,  34.50803305,  58.20802466,  24.25910863,
       -33.49739554, -37.24654542])

In [8]:
# Use the citipy module to determine city based on latitude and longitude.
from citipy import citipy

In [12]:
# Use the tuple function to display the latitude and longitude combinations.
for coordinate in coordinates:
    print(citypy.nearest_city(coordinate[0], coordinate[1]).city_name, citypy.nearest_city(coordinate[0], coordinate [1]).country_code)

In [13]:
#Trying to get more than 500 cities, increase your size limit on the np.random.uniform() 6.1.5
np.random.uniform(-90.000, 90.000, size=50)

array([-40.24375759, -83.2776733 ,  -7.72255864,   6.08249787,
       -77.71740714, -88.43390734, -33.61484538,  49.74150665,
       -54.36878894, -41.74040876, -41.76299364,  77.01111073,
       -36.11574259, -43.02158367,  51.56432752, -80.83200906,
        74.53070073, -28.73889439, -21.71701939,  20.70417496,
        64.42696645,  88.22548163,  15.97366049,   5.5134496 ,
       -40.03445322,  43.21110128, -85.97549921, -15.79623522,
        31.05521097, -67.02844326,  12.48895449, -48.98275029,
        62.3763721 , -35.93680052,   2.99514567,  68.06452437,
        51.70429052,  74.49907915, -12.31691195,  83.76298051,
        52.49788501, -53.04759096,  26.63038304,  81.45599557,
        76.90862732,  21.60312049, -38.96588383, -49.67134356,
       -69.92306765,  -5.350415  ])

In [14]:
# Use the citipy module to determine city based on latitude and longitude.
from citipy import citipy

In [15]:
# Use the tuple() function to display the latitude and longitude combinations.
for coordinate in coordinates:
    print(citipy.nearest_city(coordinate[0], coordinate[1]).city_name,
          citipy.nearest_city(coordinate[0], coordinate[1]).country_code)

In [16]:
# Create a list for holding the cities.
cities = []
# Identify the nearest city for each latitude and longitude combination.
for coordinate in coordinates:
    city = citipy.nearest_city(coordinate[0], coordinate[1]).city_name

    # If the city is unique, then we will add it to the cities list.
    if city not in cities:
        cities.append(city)
# Print the city count to confirm sufficient count.
len(cities)

0

In [17]:
#Trying to get more than 500 cities, increase your size limit on the np.random.uniform() 6.1.5
np.random.uniform(-90.000, 90.000, size=50)

array([-10.47965194,   7.2032635 ,  12.10991469, -29.47593957,
       -42.46704395,  35.18509377, -25.46387146,  14.93719958,
       -37.34366216,  20.69266215, -13.60578069, -47.675249  ,
        -3.81854457,  46.70618146, -16.94915087, -43.29344548,
        21.88211011, -40.80092912, -24.43318707,  41.27947193,
       -11.17767815, -34.74549305, -28.11314633, -44.12654269,
        63.92854274, -69.73929337,  39.22849061, -21.88748094,
        70.22388496, -35.5822601 , -43.62138397,  53.71531442,
        11.73121758, -31.1770465 , -33.16513652,  13.58712586,
        -6.12541858, -84.03175745, -19.37790938, -26.27288732,
         7.456424  ,  62.00959238, -37.86951227,  64.96734921,
       -84.35584586,  20.78161702, -40.29384076,  23.09271126,
        77.36960636, -42.11642046])

In [ ]:
#its not working!! 